// Generated by Wrangler on Wed Sep 04 2024 11:25:36 GMT-0700 (Mountain Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

/// <reference types="@cloudflare/workers-types" />

interface CloudflareEnv {
    DATABASE: D1Database;
    KV: KVNamespace<string>;
    R2_BUCKET: R2Bucket;
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL: string;
}
